server:
  port: 8080
  tomcat:
    threads:
      max: 200

spring:
  application:
    name: book-reading-online
  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: ${DATA_SOURCE_URL:jdbc:mysql://localhost:3306/book}
    username: ${DATA_SOURCE_USERNAME:root}
    password: ${DATA_SOURCE_PASSWORD:123456}
    driver-class-name: ${DATA_SOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    hikari:
      maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE:20}
  data.web.pageable.one-indexed-parameters: true
  jpa:
    open-in-view: false
logging:
  pattern:
    level: '%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]'
  level:
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE_SQL:DEBUG}
    org.hibernate.type.descriptor.sql: ${LOG_LEVEL_HIBERNATE_SQL_VALUE:DEBUG}

jwt-config:
  secretKey: ${JWT_SECRET_KEY:}
  expiryDuration: ${JWT_EXPIRY_DURATION:30d}
  refreshDuration: ${JWT_REFRESH_DURATION:60d}

aws-config:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY:}
    secret-key: ${AWS_S3_SECRET_KEY:+N}
    region: ${AWS_S3_REGION:}
    bucket: ${AWS_S3_BUCKET:}
    signature-duration: ${AWS_S3_SIGNATURE_DURATION:30m}